from ..... import rule
from .....facts import EnumFact
from .....models import Replace, SourceRewrite


@rule
def redundant_enum_value(subject: EnumFact) -> bool:
    """Detect explicit enum values that standard `auto()` would preserve.

    Definition
    ----------
    Inspect direct subclasses of `Enum`, `IntEnum`, `StrEnum`, `Flag`, and `IntFlag`.
    A literal is redundant when it equals the next value generated by the standard
    enum implementation. Classes that override `_generate_next_value_` are excluded.
    String values in a plain `Enum` remain explicit because its `auto()` value is an
    increasing integer.

    Evidence
    --------
    Every finding identifies one assignment whose runtime value is preserved by `auto()`.

    Exceptions
    ----------
    Keep explicit protocol values, aliases, compatibility values, mixed value types,
    custom generation, and spelling whose public meaning differs from the member name.

    Examples
    --------
    `FAST = "fast"` in a `StrEnum`, `FIRST = 1` in an `Enum`, and `READ = 1` in
    a `Flag` are replaceable by `auto()`. `HTTP_OK = 200` and `PUBLIC = "public-name"`
    remain explicit.

    References
    ----------
    Cites "The Python Standard Library", enum documentation for `auto` and `_generate_next_value_`
    """
    return any(
        member.explicit_value == member.standard_auto_value
        for enum in subject.enums
        if not enum.overrides_generate_next_value
        for member in enum.members
    )


@redundant_enum_value.fix(is_default=True)
def use_auto(subject: EnumFact) -> list[SourceRewrite]:
    """State each member whose value repeats the standard result as `auto()`."""
    return [
        Replace(target=member.value_node, source="auto()")
        for enum in subject.enums
        if not enum.overrides_generate_next_value
        for member in enum.members
        if member.value_node is not None and member.explicit_value == member.standard_auto_value
    ]
