from .base import Oracle as Oracle
from .base import required_row_value as required_row_value
from .base import scalar_row as scalar_row
from .clippy import ClippyOracle as ClippyOracle
from .javascript.eslint import ESLintOracle as ESLintOracle
from .javascript.magnitude import ESLintMagnitudeOracle as ESLintMagnitudeOracle
from .native.clang import ClangTidyOracle as ClangTidyOracle
from .native.clang_magnitude import ClangTidyMagnitudeOracle as ClangTidyMagnitudeOracle
from .native.cppcheck import CppcheckOracle as CppcheckOracle
from .python.magnitude import PylintMagnitudeOracle as PylintMagnitudeOracle
from .python.pylint import PylintOracle as PylintOracle
from .ruff import RuffOracle as RuffOracle
