from ..... import rule
from .....facts import AuthorshipSignalFact
from .....models import Count


@rule
def ai_associated_pattern_count(
    subject: AuthorshipSignalFact, *, providers: tuple[str, ...] = ()
) -> Count:
    """Count exact AI-associated style patterns reported by external analyzers.

    Definition
    ----------
    Read provider-neutral evidence generated by tools such as Vale AI Tells or Pangram.
    Count every selected pattern occurrence without combining phrase likelihood multiples.
    A provider baseline is retained as a separate measurement because observed count,
    expected count, and authorship probability are different quantities.

    Evidence
    --------
    Each finding preserves the provider, provider version, external rule, matched text, source
    range, and any provider-reported relative likelihood. The configured provider filter is
    case-insensitive. An empty filter includes every provider. The value is the number of selected
    pattern occurrences across every eligible segment.

    Exceptions
    ----------
    A pattern can be intentional, required terminology, quoted text, or ordinary prose in another
    domain or language. This rule reports selected house-style evidence and never claims that a
    person or model authored the text. `providers` selects which analyzers count, matched without
    regard to case, and an empty selection includes every provider the evidence holds.

    Examples
    --------
    A document with twenty Pangram evidence instances returns `20`. If Pangram reports an
    expected baseline near four, the baseline stays a separate finding rather than being
    converted into an AI probability. A Vale alert for `At its core` contributes one count.

    References
    ----------
    Cites "Pangram documentation", How our AI detector works
    https://www.pangram.com/research/how-it-works
    Cites "Vale AI Tells"
    https://github.com/tbhb/vale-ai-tells
    Cites "Monitoring AI-Modified Content at Scale"
    https://arxiv.org/abs/2403.07183
    """
    return sum(
        len(patterns)
        for segment in subject.segments
        if segment.is_eligible
        for provider, patterns in segment.patterns_by_provider.items()
        if not providers or provider in providers
    )
